apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: {{ include "tenant.name" . }}
  labels:
    {{- include "tenant.labels" . | nindent 4 }}
spec:
  email: "{{ include "tenant.email" . }}"
  masterCredentialsRef:
    name: system-seed
  organizationName: "{{ .Values.tenant.organizationName }}"
  passwordCredentialsRef:
    name: "{{ .Values.tenant.organizationName }}-admin-secret"
  systemMasterUrl: "{{ include "system.master-url" . }}"
  tenantSecretRef:
    name: "{{ .Values.tenant.organizationName }}-tenant-secret"
    namespace: "{{ .Release.Namespace  }}"
  username: "{{ include "tenant.adminId" . }}"
