{{- if .Values.s3Auth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3-auth.name" . }}
  labels:
    {{- include "apimanager.labels" . | nindent 4 }}
{{- include "s3-auth.secret" . }}
type: Opaque
{{- end }}